basePath: /
host: unripe-bison.cnine.me
info:
  contact:
    name: Github
    url: https://github.com/Aysnine/unripe-bison
  description: "Web server example by GoFiber⚡️ and CockroachDB\U0001F4D6"
  license:
    name: MIT
  title: UnripeBison Server API
  version: v0
paths:
  /api/books:
    get:
      operationId: get-books
      produces:
      - application/json
      summary: books
    post:
      operationId: add-book
      produces:
      - application/json
      summary: books
  /api/hongkong-weather:
    get:
      operationId: get-hongkong-weather
      produces:
      - application/json
      summary: hongkong weather info
  /api/random-anime-image:
    get:
      operationId: get-random-anime-image
      produces:
      - application/json
      summary: hongkong weather info
  /chat:
    get:
      operationId: chat
      produces:
      - application/json
      summary: global chat room
swagger: "2.0"
