name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      env:
        DATABASE_CONNECTION: ${{ secrets.DATABASE_CONNECTION }}
      run: go test ./...

  simple-build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: go build -o unripe-bison-app

    - name: Copy dist folder
      run: |
        mkdir dist
        cp unripe-bison-app dist/
        cp .github/workflows/app.sh dist/
        echo DATABASE_CONNECTION=${{ secrets.DATABASE_CONNECTION }} >> dist/.env

    - uses: mdallasanta/ssh-scp-deploy@v1.1.0
      with:
        local: './dist/*'                                            # Local file path - REQUIRED false - DEFAULT ./
        remote: '~/'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
        host: ${{secrets.DEPLOY_HOST}}                               # Remote server address - REQUIRED true
        user: ${{secrets.DEPLOY_USER}}                               # Remote server user - REQUIRED true
        password: ${{secrets.DEPLOY_PASSWORD}}                       # User password - REQUIRED at least one of "password" or "key" 
        post_upload: chmod u+x ./app.sh; ./app.sh restart
        ssh_options: -o StrictHostKeyChecking=no
        scp_options: -v
